### ISSUE TITLE
Constant Crashes when NootedRed is used on Sonoma.

### ISSUE THREAD

**Issue by luipancake1** [ChefKissInc/NootedRed#286] opened 2024-07-31 21:20 UTC
### macOS Version

Sonoma

### What is your CPU's model?

Ryzen 3 3200G

### Please describe the behaviour in detail.

Booting up without NootedRed causes a lot of slowdown and a not smooth experience, but adding NootedRed causes crashing after about a minute of use with a lot of freezing and slowdown. Booting it backup tries to send a report to apple but still restarts again and does the same thing.

### What should've happened instead?

Adding NootedRed not making the system restart after a minute.

**Comment by VisualEhrmanntraut** [comment] 2024-07-31 21:22
Duplicate of #235

**Closed by VisualEhrmanntraut** 2024-07-31 21:22 UTC
Labels: Duplicate
