### ISSUE TITLE
AMD Radeon GCN5 VEGA 8 iGPU Flickering screen

### ISSUE THREAD

**Issue by royaldragonit** [ChefKissInc/NootedRed#330] opened 2024-11-15 14:17 UTC
### macOS Version

None

### What is your CPU's model?

AMD Ryzen 7 5800U

### Please describe the behaviour in detail.

Add NootedRed kext, my iGPU worked with 2GB. But screen is flickering

### What should've happened instead?

Add NootedRed kext, my iGPU worked with 2GB. But screen is flickering

### If applicable, attach the .gpuRestart, .panic, etc file related to this issue.

https://github.com/user-attachments/assets/e2211ba1-e016-4dd2-a5e3-d5da414ad2df

**Comment by royaldragonit** [comment] 2024-11-15 14:34
EFI and aida64 report here [](https://drive.google.com/drive/folders/1Pl921dQnZZFDIIdVjZHb2TYRzSVyqOJx?usp=sharing)

**Comment by VisualEhrmanntraut** [comment] 2024-11-18 14:10
Duplicate of #301

**Closed** 2024-11-18 14:10 UTC
Labels: Duplicate
