### ISSUE TITLE
H.265 can be hardware decoded successfully， but H.264 cannot be hardware decoded

### ISSUE THREAD

**Issue by Kanepan** [ChefKissInc/NootedRed#163] opened 2023-09-07 06:21 UTC
The latest version of NootedRed is running very smoothly. To test the VNC functionality, I added the "-nredvcn" args. Here's an interesting thing: when streaming with parsec, H.264 cannot be hardware decoded, but H.265 can be hardware decoded successfully. I hope this information is helpful to you.

**System Information:**
 - macOS Version: [ macOS 13.5.1]
 - CPU: [AMD Ryzen 5 5800h]

**Comment by VisualEhrmanntraut** [comment] 2023-09-07 06:29
Duplicate of #28

**Closed by VisualEhrmanntraut** 2023-09-07 06:29 UTC
Labels: Duplicate
