### ISSUE TITLE
RDNA3 support?

### ISSUE THREAD

**Issue by js-6951** [ChefKissInc/NootedRed#238] opened 2024-03-26 11:27 UTC
### macOS Version

Ventura

### What is your CPU's model?

7840U

### Please describe the feature in detail.

Is RDNA 3 (780M) support in the pipeline, will it be a reality sometime in the future?

### What alternatives have you tried, if any?

Not tried it yet.

### Feature request submission terms

- [X] I am using the latest version of NootedRed, thereby extension the feature is not already present.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The feature being present in NootedRed makes sense.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by VisualEhrmanntraut** [comment] 2024-03-26 11:30
Duplicate of #92

**Closed by VisualEhrmanntraut** 2024-03-26 11:30 UTC
Labels: Duplicate
