### ISSUE TITLE
Rembrandt Support

### ISSUE THREAD

**Issue by vodangtue** [ChefKissInc/NootedRed#254] opened 2024-04-20 02:19 UTC
### macOS Version

None

### What is your CPU's model?

AMD Ryzen 5 7535HS with Radeon Graphics

### Please describe the feature in detail.

I want NootedRed to be able to work with Rembrandt APU. Thanks!!

### What alternatives have you tried, if any?

I have tried NootedRed but I have read requirements again then I know it not supported :).

**Comment by VisualEhrmanntraut** [comment] 2024-04-20 08:48
Duplicate of #92

**Closed by VisualEhrmanntraut** 2024-04-20 08:48 UTC
Labels: Duplicate

**Comment by ExtremeXT** [comment] 2024-04-20 10:00
@github-actions[bot] iMac1,1 2011 model bomb moment
