### ISSUE TITLE
Ryzeb 5 7540U Support?

### ISSUE THREAD

**Issue by taqieallah** [ChefKissInc/NootedRed#287] opened 2024-08-02 23:11 UTC
### macOS Version

None

### What is your CPU's model?

Ryzeb 5 7540U

### Please describe the feature in detail.

does nootedred support AMD Radeon™ 740M? im buying a new laptop but i want to check if its working,

### What alternatives have you tried, if any?

nope

**Comment by hg13bs** [comment] 2024-08-02 23:14
not supported

**Comment by L123er** [comment] 2024-08-03 11:10
Wait, they are also very hard.

**Comment by VisualEhrmanntraut** [comment] 2024-08-03 11:11
Duplicate of #92

**Closed by VisualEhrmanntraut** 2024-08-03 11:11 UTC
Labels: Duplicate
