### ISSUE TITLE
Erratic colours on 5700G + Big Sur

### ISSUE THREAD

**Issue by rtd1250** [ChefKissInc/NootedRed#199] opened 2023-11-17 19:19 UTC
**Describe the bug**
Colour is not correct on HDMI output with NootedRed enabled.

**To Reproduce**
1. Enable NootedRed
2. Reboot
3. Be greeted with LSD desktop

**Expected behavior**
Colours should be displayed correctly, as in black should be black instead of green.

**Screenshots**
<img width="1470" alt="screenshot" src="https://github.com/ChefKissInc/NootedRed/assets/47224354/1615d434-7ff8-4c37-8d24-7f9012d77307">

**System Information:**
 - macOS Version: macOS 11.7.10
 - CPU: AMD Ryzen 7 5700G
 - Motherboard: MSI X570
 - SMBIOS: iMacPro1,1

**Additional context**
Changing resolutions and colour depth doesn't really seem to do anything. This only happens on HDMI output, screenshots look fine (the screenshot above was taken with an HDMI grabber). The acceleration itself does work and in the About window it reports as "AMD Radeon Graphics 1 GB".

**Comment by VisualEhrmanntraut** [comment] 2023-11-19 11:09
Duplicate of #58

**Comment by VisualEhrmanntraut** [comment] 2023-11-19 11:09
Oops, wrong number

**Comment by VisualEhrmanntraut** [comment] 2023-11-19 11:10
Duplicate of #65

**Closed** 2023-11-19 11:13 UTC
Labels: Bug
