### ISSUE TITLE
Freezing Randomly(Kernel Panic) when opening wallpaper section and Apple Music

### ISSUE THREAD

**Issue by arnofrxdd** [ChefKissInc/NootedRed#329] opened 2024-11-11 03:33 UTC
### macOS Version

Sequoia

### What is your CPU's model?

AMD Ryzen 7 5800H

### Please describe the behaviour in detail.

When you open Apple Music, it will cause kernel panic or freezing for few seconds. Same goes for wallpaper section in settings and using dynamic wallpaper

doesn't happen when using animated wallpapers

yes I'm using the latest build.

### What should've happened instead?

Should work smoothly.

**Comment by nisel11** [comment] 2024-11-11 08:06
duplicate of https://github.com/ChefKissInc/NootedRed/issues/235

**Closed** 2024-11-11 13:46 UTC
Labels: Duplicate
