### ISSUE TITLE
Constant system crashes (usually caused by apple apps)

### ISSUE THREAD

**Issue by grantuze** [ChefKissInc/NootedRed#265] opened 2024-05-17 17:26 UTC
### macOS Version

Sonoma

### What is your CPU's model?

AMD Ryzen 5 3500U

### Please describe the behaviour in detail.

When you open ex. Apple Podcasts, the system crashes and then reboots

### What should've happened instead?

The podcasts app should've ran like in Ventura

### If applicable, attach the .gpuRestart, .panic, etc file related to this issue.

This is NootedRed problem, no need for logs.

**Comment by yarecco** [comment] 2024-05-18 15:47
Can't confirm. Podcasts App works without any issues on Sonoma 14.5 with NootedRed.
![Screenshot 2024-05-18 at 16 46 01](https://github.com/ChefKissInc/NootedRed/assets/29832803/08d4bf0d-a9d2-4d85-9cf6-fe9c3dcbaec2)

**Comment by VisualEhrmanntraut** [comment] 2024-05-29 15:40
Duplicate of #235

**Closed by VisualEhrmanntraut** 2024-05-29 15:40 UTC
Labels: Duplicate
