### ISSUE TITLE
Black screen on boot

### ISSUE THREAD

**Issue by Trijal08** [ChefKissInc/NootedRed#181] opened 2023-10-01 15:43 UTC
**Describe the bug**
My screen goes black after booting. I think the graphics are not working for my CPU. However It did not show the black screen on an [older version of NootedRed](https://github.com/ChefKissInc/NootedRed/actions/runs/5846412583). 

**To Reproduce**
Just booting into macOS Sonoma. 

**Expected behavior**
I expected the kext to just allow me in to macOS. 

**Screenshots**
Screen completely Black but backlight is on. 

**System Information:**
 - macOS Version: macOS 14 (Sonoma)
 - CPU: AMD Ryzen 3 3700U
 - Manufacturer: Hewlett-Packard (HP)
 - Model: HP Laptop 15-ef0038ca
 - Country: Canada

**Comment by VisualEhrmanntraut** [comment] 2023-10-01 15:47
Too old to pin-point issue

**Comment by DepsCian** [comment] 2023-10-01 17:49
Same. This is not the first time I have gotten this error. In the last issue I was advised to use the latest build, but that helped for a while.

**Comment by Trijal08** [comment] 2023-10-02 00:11
> Too old to pinpoint issue

What do you mean by that. Does that mean I have to use the older version?

**Comment by hoaug-tran** [comment] 2023-10-03 08:45
I had the same problem when using the latest kext. Using older version kext does not work

**Comment by hoaug-tran** [comment] 2023-10-03 08:54
hmm, im using this version: https://github.com/ChefKissInc/NootedRed/actions/runs/6157959609
and its ok. with lastest version i got black screen sometimes ( Not every time it boots, but sometimes it happens ). i will try kext you send me above

**Comment by VisualEhrmanntraut** [comment] 2023-10-03 08:55
@hoaug-tran Oh, so it’s not the fw injection? What SMBIOS are you using

**Comment by Trijal08** [comment] 2023-10-03 12:26
> @hoaug-tran Oh, so it’s not the fw injection? What SMBIOS are you using

Sorry to be nosy, but I am using the MacBookPro16,3 as you said in the website. Is it ok?

**Comment by hoaug-tran** [comment] 2023-10-03 12:28
@Trijal08 its OK

**Comment by Trijal08** [comment] 2023-10-03 12:36
> @Trijal08 its OK

BRO NO WAY, I know how to fix it. Just enable "Keep data such as "Datahub"" in PlatformInfo/Quirks.
![image](https://github.com/ChefKissInc/NootedRed/assets/97483939/0a22e053-e0d4-49b4-b382-772cb60e11ce)
Case closed for me!

**Comment by Trijal08** [comment] 2023-10-03 13:07
> @hoaug-tran Oh, so it’s not the fw injection? What SMBIOS are you using

IT IS NOT WORKIN AGAIN BRO!!! TELL ME WHAT DO I DO! Here, take my fricking [EFI](https://drive.google.com/file/d/1iqsp4rMdRrCxTMzBr6KME_oL5UUutM56/view?usp=sharing).

**Comment by hoaug-tran** [comment] 2023-10-03 13:09
@Trijal08 😂🤦‍♂️  wait Visual check it

**Comment by Trijal08** [comment] 2023-10-03 13:10
> @Trijal08 😂🤦‍♂️ wait Visual check it

WDYM? What did you do to fiix that thing!

**Comment by Trijal08** [comment] 2023-10-03 13:13
@VisualEhrmanntraut PLS HELPO BROU

**Comment by Trijal08** [comment] 2023-10-03 13:14
@VisualEhrmanntraut IT IS NOT WORKIN AGAIN BRO!!! TELL ME WHAT DO I DO! Here, take my fricking [EFI](https://drive.google.com/file/d/1iqsp4rMdRrCxTMzBr6KME_oL5UUutM56/view?usp=sharing).

**Comment by hoaug-tran** [comment] 2023-10-03 13:15
@Trijal08 i told you wait, he needs to be able to check. SO PLEASE WAIT. DONT SPAM. OK ?

**Comment by Trijal08** [comment] 2023-10-03 13:16
> @Trijal08 i told you wait, he needs time to be able to check. SO PLEASE WAIT. DONT SPAM. OK ?

Bro are you admin? I never knew bro sorry.

**Comment by hoaug-tran** [comment] 2023-10-03 13:18
@Trijal08 no. im not bro. i am a user who got the same error as you. Our job is just to wait, be patient. Try using an older kext to see if it's better. Have you tried yet ?

**Comment by VisualEhrmanntraut** [comment] 2023-10-03 13:20
Enough.

**Comment by VisualEhrmanntraut** [comment] 2023-10-04 18:23
Please try https://github.com/ChefKissInc/NootedRed/actions/runs/6409958778 once it builds

**Comment by VisualEhrmanntraut** [comment] 2023-10-05 21:34
Unlocked for providing feedback. Please be descriptive (exact behaviour, logs, etc), else your input will be useless.

**Comment by DepsCian** [comment] 2023-10-06 06:46
Black screen not fixed for me. P.S: I'm using HDMI, R3 2200G, Ventura.

**Comment by VisualEhrmanntraut** [comment] 2023-10-06 07:02
@DepsCian > Please be descriptive (exact behaviour, logs, etc)

**Comment by DepsCian** [comment] 2023-10-06 07:05
@VisualEhrmanntraut  > I'd like to send logs, but I don't know where to look at them.

**Comment by binxr** [comment] 2023-10-06 16:02
There are times when my Sonoma just has a black screen, and the numlock is active, (which was not supposed to be active) and after many restarts it finally turns off the numlock and the image appears.

same issue on Monterey, (I upgrade Monterey to Sonoma.)
using a Vega 11 and a Ryzen 5 3350gPRO.

**Comment by binxr** [comment] 2023-10-08 03:26
@VisualEhrmanntraut you can help me? with this bug?

**Comment by hoaug-tran** [comment] 2023-10-10 06:21
@VisualEhrmanntraut here is my logs, Who knows, maybe something can help. https://drive.google.com/file/d/1BaL4XtGQPdae4h5nux0YpnPQGVL-9UzF/view?usp=drivesdk

**Comment by VisualEhrmanntraut** [comment] 2023-10-20 13:12
Is this still relevant with the latest commit

**Comment by laris** [comment] 2023-10-27 16:07
I use latest build and also have same issue, after boot into login homepage, the screen will be black status but the mouse arrow can be moved freely, but the background is black totally. Thank after wait about 1 minutes the normal login home page will be ready and show in screen.

log can be checked from here: https://github.com/ChefKissInc/NootedRed/issues/186#issuecomment-1783144129

**Comment by GeantW0rld** [comment] 2023-11-10 22:24
get same issue with internal screen on my laptop but when I plug in the hdmi I can get the display on the external montior

**Comment by VisualEhrmanntraut** [comment] 2023-11-11 15:04
Unable to reproduce. Closing due to staleness.

**Closed by VisualEhrmanntraut** 2023-11-11 15:04 UTC
Labels: Bug

**Comment by epokuser** [comment] 2024-09-18 17:37
hi still happens on amd radeon vega 8 laptop based on zen+

**Comment by epokuser** [comment] 2024-09-23 12:44
> > hi still happens on amd radeon vega 8 laptop based on zen+
> 
> Known issues and can be fixed with these methods
> 
>     * Use -NRedDPDelay at boot-args
> 
>     * Use SSDT-PNLF with _UID 17 or 18 on SSDTTime (19 gives blackscreen sometimes)
> 
>     * Inject EDID through OpenCore DeviceProperties



hi I tried NRedDPDelay at boot-args yet it did the same thing...
and the last two methods idk how to do them...

**Comment by alvindimas05** [comment] 2024-09-24 10:26
> > > hi still happens on amd radeon vega 8 laptop based on zen+
> > 
> > 
> > Known issues and can be fixed with these methods
> > ```
> > * Use -NRedDPDelay at boot-args
> > 
> > * Use SSDT-PNLF with _UID 17 or 18 on SSDTTime (19 gives blackscreen sometimes)
> > 
> > * Inject EDID through OpenCore DeviceProperties
> > ```
> 
> hi I tried NRedDPDelay at boot-args yet it did the same thing... and the last two methods idk how to do them...

You can tag me on AMD OSX Discord or ChefKissInc telegram to help you (My username is the same)

**Comment by RickiThaDragon** [comment] 2024-11-24 05:52
Installed macOS Catalina per Dortania Desktop Guide for AMD. The PC Installed is HP Probook Ryzen 7 4700U. Everything works great after Install. So i had previously Built NootedRed.kext AND went ahead and placed it where it goes, snapshoted Plist went to boot up and it finishes boot like it should just have a black screen now.  

So I removed WhateverGreen.kext (Booted) Same Problem
Put it Back in there with Nootedred still same Problem. Imusing Shanee patches instead of algreys the two that your allowed to turn on and off depending upon which you want to use. (Could that be the Problem)?

Any helpful Feedback Or Solutions Would Be great. 
Minimal Kexts Installed 
Lilu, VoodooHDA, Virtual SMC, WhateverGreen, Realtek Ethernet, wIfi card is incompatible SO no wifi kexts and no bluetooth kexts are installed either. XHCI Unsupported, USB InjectAll,  thats it. Thanks.
