### ISSUE TITLE
Some content and heavy applications cause GPU panics (hangs) or artefacts

### ISSUE THREAD

**Issue by VisualEhrmanntraut** [ChefKissInc/NootedRed#13] opened 2023-02-22 18:22 UTC
Seems to be causing GPU page faults. Related dmesg attached below
[dmesg-1676548999.txt](https://github.com/NootInc/WhateverRed/files/10807078/dmesg-1676548999.txt)

**Comment by ChefKissInc** [comment] 2023-02-23 13:30
Issue severity has been reduced. Only some videos cause this now

**Comment by ChefKissInc** [comment] 2023-03-01 05:26
Seems to be related to VRAM size. Increasing VRAM on my laptop from 512MB to 1GB resolves it. Maybe because macOS thinks it's a dGPU, it's not optimising how much VRAM it can use. Requires more research

**Comment by ChefKissInc** [comment] 2023-03-31 19:07
Hey @jalavoui. I've been taking peaks at your thread. You've given us a few useful clues here and there for a few of these fixes. Thanks for your suggestions. Would you mind explaining what this patch does?
P.S. It would be nice if you joined our Telegram group. It is here: https://t.me/NootInc

**Comment by bobouncle** [comment] 2023-06-12 14:42
todesk application cannot be used.  is crash

**Comment by hoppingninja666** [comment] 2023-06-17 17:59
Playing a YouTube video Firefox causes hangup of the whole system and does not recover from this state. I am using macOS Monterey. In chrome and chrome based browsers, first few minutes when you use the search bar, the whole browser window turns pinkish and recovers after a while, and becomes smooth after a few of such hangup. I could play in 4k using chromium based browsers.

**Comment by ChefKissInc** [comment] 2023-06-17 18:00
@hoppingninja666 It’s weird, some systems have problems with Chrome, some with Firefox, some not at all. Pretty weird

**Comment by ChefKissInc** [comment] 2023-06-18 13:10
macOS wasn't brave enough to handle it

**Comment by war1644** [comment] 2023-07-03 04:30
me too
1. Continuous long stuttering when entering text
2. There is a lag when opening the image
3. Other

**Comment by war1644** [comment] 2023-07-03 04:31
> 现在我用最新的驱动文件，也遇到了同样的情况，但是不会崩溃，一张一张卡的图片，整个画面卡了一会儿，不动了，过一会儿就可以用了

+1

**Comment by ChefKissInc** [comment] 2023-07-03 09:26
I have not forgotten about the issues; you don't need to create bumps.

**Comment by sinsin700** [comment] 2023-07-05 22:53
I can walk with Brave Browser but lag when opened I try to wait for it to be opened

**Comment by joederpoliveira** [comment] 2023-07-06 18:12
First... Sorry for my bad english.

But. If you need Chrome like I do... This is what I did:

1) Install Chrome (duhh);
2) Open Terminal and paste "/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --args --disable-gpu" (without quotes);
3) Go to Chrome's settings and look for something like "Use hardware acceleration" and disable this option;
4) restart the browser.

I've done that and still haven't had any issues.

**Comment by ChefKissInc** [comment] 2023-07-06 18:13
@joederpoliveira https://nootinc.github.io/nred#chrome-chromium-based-browsers-and-apps-like-sublime-text-cause-graphical-artefacts-amongst-other-problems

**Comment by joederpoliveira** [comment] 2023-07-06 19:33
> @joederpoliveira https://nootinc.github.io/nred#chrome-chromium-based-browsers-and-apps-like-sublime-text-cause-graphical-artefacts-amongst-other-problems

The problem is that opening Chrome already caused the crash. I just got it the way I posted above.

**Comment by joederpoliveira** [comment] 2023-07-06 19:35
I didn't even have time to enter chrome://flags.

**Comment by ChefKissInc** [comment] 2023-07-06 19:42
@joederpoliveira Sorry, I just meant that I already have this as an entry

**Comment by joederpoliveira** [comment] 2023-07-06 19:55
> @joederpoliveira Sorry, I just meant that I already have this as an entry

No problem. It turns out that my post can help someone who is not able to get into Chrome to disable the flag. That's why I decided to post it here. I think it should work on other Chromium based browsers.

**Comment by gorouflex** [comment] 2023-07-16 00:41
If I use Microsoft Edge and watch a video on that, it will crash (or blink the screen) for some reasons, also that may happen to some application. Can be fixed by turn off **`Hardware Acceleration`** setting.

**Comment by winktool** [comment] 2023-08-19 15:54
> Seems to be related to VRAM size. Increasing VRAM on my laptop from 512MB to 1GB resolves it. Maybe because macOS thinks it's a dGPU, it's not optimising how much VRAM it can use. Requires more research

plz how to change vram?

**Comment by ChefKissInc** [comment] 2023-08-19 15:54
@winktool Smokeless-UMAF

**Comment by winktool** [comment] 2023-08-19 16:27
> Smokeless-UMAF

love you

**Comment by Woohwah** [comment] 2023-08-23 06:52
On Ventura I got this issue when I open the App Store

**Comment by liuliu11ss** [comment] 2023-08-27 12:33
5600H CPU opens an application or a page of the operating system will get stuck, and the system will respond later. The latest version of the driver, MAC OS is ventura.

**Comment by VisualEhrmanntraut** [comment] 2023-08-27 12:34
Thanks, very useful

**Comment by VisualEhrmanntraut** [comment] 2023-09-04 19:35
I am working on a potential fix. I think what I'm implementing will completely fix this and #137. No promises though.

**Closed** 2023-09-06 07:35 UTC
Labels: Bug
