### ISSUE TITLE
Firefox crashing system

### ISSUE THREAD

**Issue by DepsCian** [ChefKissInc/NootedRed#165] opened 2023-09-07 18:58 UTC
**Describe the bug**
Firefox crashing my system like Chrome, but without artefacts

**To Reproduce**
1. Just serf internet wia Firefox.
2. Profit

**Expected behavior**
Working browser

**System Information:**
 - macOS Version: 13.5.1 (I also use Monterey some time ago, and this issue also be)
 - CPU: Ryzen 3 2200G

**Comment by VisualEhrmanntraut** [comment] 2023-09-07 18:58
Oh really? Didn't know bro.

**Comment by VisualEhrmanntraut** [comment] 2023-09-07 18:58
Duplicate of #158

**Closed by VisualEhrmanntraut** 2023-09-07 18:58 UTC
Labels: Duplicate
