### ISSUE TITLE
Artifacts on almost every app downloaded

### ISSUE THREAD

**Issue by binxr** [ChefKissInc/NootedRed#247] opened 2024-04-08 16:42 UTC
### macOS Version

Catalina

### What is your CPU's model?

AMD Ryzen 5 3350G PRO

### Please describe the behaviour in detail.

When I try to open Chrome or Firefox or Spotify or League of Legends itself, very heavy artifacts appear in which I can no longer use the system without restarting the Hackintosh I can't open these applications And I use macOS Monterey version 12.7.4, anyone Would you know how these artifacts could disappear?
![Captura de Tela 2024-04-08 às 13 24 01](https://github.com/ChefKissInc/NootedRed/assets/133918891/8b59378f-8260-42f6-ba13-2d8484499089)
![Captura de Tela 2024-04-08 às 13 24 59](https://github.com/ChefKissInc/NootedRed/assets/133918891/4475750f-6edf-4714-8355-9b7b28b76f78)

### What should've happened instead?

Applications should appear normally without artifacts As is happening now

### Bug report submission terms

- [X] I am using the latest version of NootedRed.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The bug only happens with NootedRed enabled.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by VisualEhrmanntraut** [comment] 2024-04-08 16:43
These are all OpenGL apps. The issues tab are not a support forum for you to post your every question on.

**Comment by VisualEhrmanntraut** [comment] 2024-04-08 16:43
Duplicate of #158

**Closed by VisualEhrmanntraut** 2024-04-08 16:43 UTC
Labels: Bug
