### ISSUE TITLE
Graphics green and purple 

### ISSUE THREAD

**Issue by osenaattori** [ChefKissInc/NootedRed#204] opened 2023-11-26 21:20 UTC
### macOS Version

Big Sur

### What is your CPU's model?

Amd 5600g

### Please describe the behaviour in detail.

Graphics messed up and always forces HDR 

### What should've happened instead?

They should be working

### If applicable, attach the .gpuRestart, .panic, etc file related to this issue.

https://cdn.discordapp.com/attachments/390417898986012672/1178440888289075230/IMG_0768.jpg?ex=6576279a&is=6563b29a&hm=c496aa7daedcce0dab05d867ba8a7f065ffb773030c9f504dba5773ca4cacc49& Looks like this

### Bug report submission terms

- [X] I am using the latest version of NootedRed.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The bug only happens with NootedRed enabled.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by ExtremeXT** [comment] 2023-11-26 21:31
Duplicate of #65.

**Closed by ExtremeXT** 2023-11-26 21:31 UTC
Labels: Bug
