### ISSUE TITLE
(R5 3350GPRO VEGA 11) black screen with an older and new EFI

### ISSUE THREAD

**Issue by binxr** [ChefKissInc/NootedRed#182] opened 2023-10-03 16:09 UTC
im using IMac20,1 as suggested on website 
im building a hack with a Ryzen 5 3350gPRO with vega 11 graphics, on a A320MH biostar 
It has any new patch? To solve this? i had this problem on past but change the smbios make this problem disappear
Please try to help me!

**Comment by binxr** [comment] 2023-10-03 16:43
im trying different "solutions" here but nothing is solving

**Comment by Trijal08** [comment] 2023-10-03 18:18
> im trying different "solutions" here but nothing is solving @VisualEhrmanntraut

Bro I had the same problem with different CPU but I fixed it. Just give me your EFI OK?

**Comment by VisualEhrmanntraut** [comment] 2023-10-04 18:22
Duplicate of #181

**Closed by VisualEhrmanntraut** 2023-10-04 18:22 UTC
Labels: Duplicate
