### ISSUE TITLE
Java GUI apps hanging system and crashing

### ISSUE THREAD

**Issue by Mukunya** [ChefKissInc/NootedRed#233] opened 2024-03-09 20:11 UTC
### macOS Version

Ventura

### What is your CPU's model?

AMD Ryzen 7 5800H

### Please describe the behaviour in detail.

If you open certain java apps the system hangs for 10 seconds, a red rectangle appears and the app crashes. It even happens with software rendering set in the app (Jetbrains Gateway).

Error:
<img width="1680" alt="image" src="https://github.com/ChefKissInc/NootedRed/assets/51750827/1af64748-d333-49c8-8ee3-eaf4669768aa">

### What should've happened instead?

It should not have crashed

### If applicable, attach the .gpuRestart, .panic, etc file related to this issue.

[Kernel_2024-03-09-191708_Bans-MacBook-Pro.gpuRestart.zip](https://github.com/ChefKissInc/NootedRed/files/14547678/Kernel_2024-03-09-191708_Bans-MacBook-Pro.gpuRestart.zip)

### Bug report submission terms

- [X] I am using the latest version of NootedRed.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The bug only happens with NootedRed enabled.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by VisualEhrmanntraut** [comment] 2024-03-09 20:15
Duplicate of #158.

**Closed by VisualEhrmanntraut** 2024-03-09 20:15 UTC
Labels: Bug, Duplicate
