### ISSUE TITLE
Black screen after boot

### ISSUE THREAD

**Issue by AlfCraft07** [ChefKissInc/NootedRed#161] opened 2023-09-06 12:34 UTC
**Describe the bug**
The video adapter hangs the system while trying to initialize

**To Reproduce**
1. Add NootedRed to EFI
2. Boot with it
3. After the Apple logo and around 40% boot progress the system hangs at a black screen and OS loading stops

**Expected behavior**
The OS normally loads.

**Screenshots**

**System Information:**
 - macOS 13.5.1
 - CPU: AMD 3020e with Radeon Vega 3 graphics

**Additional context**
Recovery boots fine. Also tried booting macOS Sonoma beta with the same outcome. System worked perfectly with the older versions on both versions of macOS.

**Comment by VisualEhrmanntraut** [comment] 2023-09-06 12:37
Duplicate of #159

**Closed by VisualEhrmanntraut** 2023-09-06 12:37 UTC
Labels: Duplicate
