### ISSUE TITLE
Adding Hardware Decode to AMD Ryzen 5 5600G's iGPU

### ISSUE THREAD

**Issue by Sayor00** [ChefKissInc/NootedRed#249] opened 2024-04-09 10:45 UTC
### macOS Version

Sonoma

### What is your CPU's model?

AMD Ryzen 5 5600G

### Please describe the feature in detail.

NoothedRed does not support hardware decode that's why browsers or applications with hardware acceleration enabled, do not work.

### What alternatives have you tried, if any?

It should support hardware decode

### Feature request submission terms

- [X] I am using the latest version of NootedRed, thereby extension the feature is not already present.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The feature being present in NootedRed makes sense.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by VisualEhrmanntraut** [comment] 2024-04-09 10:45
Duplicate of #28

**Closed by VisualEhrmanntraut** 2024-04-09 10:45 UTC
Labels: Duplicate
