### ISSUE TITLE
macos15.0.1raven boot will stay at applekeystore for a long time

### ISSUE THREAD

**Issue by Win10Q** [ChefKissInc/NootedRed#315] opened 2024-10-20 14:11 UTC
### macOS Version

None

### What is your CPU's model?

AMD RYZEN 3500u

### Please describe the behaviour in detail.

i use the latest nootedred

### What should've happened instead?

it will be fast

**Comment by VisualEhrmanntraut** [comment] 2024-10-20 14:11
idk what you expect me to do with this information

**Comment by VisualEhrmanntraut** [comment] 2024-10-20 14:12
as in, there's nothing I can do with it :/

**Comment by VisualEhrmanntraut** [comment] 2024-10-20 14:15
oh, wait

**Comment by VisualEhrmanntraut** [comment] 2024-10-20 14:15
duplicate of #306

**Closed by VisualEhrmanntraut** 2024-10-20 14:15 UTC
Labels: Duplicate
